require: rubocop-rails
AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.4
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/*
    - vendor/**/*
    - db/migrate/*
    - 'config/deploy.rb'
    - 'config/deploy/**/*'
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
